import type { SecurityEvent } from '../types'

// Hardcoded stand-in for the API (React Query + mockapi.io replace this on Day 5).
// Annotated as SecurityEvent[] so every object is checked against the interface:
// a typo'd severity, a wrong status string, or a missing required field fails to compile.
export const mockEvents: SecurityEvent[] = [
  {
    id: 'evt-001',
    timestamp: '2026-06-13T08:42:00Z',
    severity: 'critical',
    description: 'Multiple failed root login attempts from a single host',
    source: 'Auth Service',
    status: 'open',
  },
  {
    id: 'evt-002',
    timestamp: '2026-06-13T09:15:00Z',
    severity: 'high',
    description: 'Port scan detected across the 10.0.0.0/24 subnet',
    source: 'IDS',
    status: 'investigating',
    assignedTo: 'a.petrova',
  },
  {
    id: 'evt-003',
    timestamp: '2026-06-12T14:03:00Z',
    severity: 'medium',
    description: 'SQL injection attempt blocked on /api/login',
    source: 'WAF',
    status: 'resolved',
    assignedTo: 'j.silva',
  },
  {
    id: 'evt-004',
    timestamp: '2026-06-10T07:30:00Z',
    severity: 'low',
    description: 'TLS certificate for mail.internal expires in 14 days',
    source: 'Monitoring',
    status: 'open',
  },
  {
    id: 'evt-005',
    timestamp: '2026-06-13T11:58:00Z',
    severity: 'critical',
    description: 'Ransomware signature detected on endpoint WK-204',
    source: 'EDR',
    status: 'investigating',
    assignedTo: 'm.okafor',
  },
  {
    id: 'evt-006',
    timestamp: '2026-06-13T06:20:00Z',
    severity: 'high',
    description: 'Large outbound data transfer to unrecognized domain',
    source: 'DLP',
    status: 'open',
  },
  {
    id: 'evt-007',
    timestamp: '2026-06-12T22:47:00Z',
    severity: 'medium',
    description: 'Impossible-travel login: NL then BR within 10 minutes',
    source: 'Auth Service',
    status: 'investigating',
    assignedTo: 'a.petrova',
  },
  {
    id: 'evt-008',
    timestamp: '2026-06-11T16:10:00Z',
    severity: 'low',
    description: 'Blocked inbound connection on deprecated port 23 (Telnet)',
    source: 'Firewall',
    status: 'resolved',
  },
  {
    id: 'evt-009',
    timestamp: '2026-06-13T10:05:00Z',
    severity: 'high',
    description: 'Unexpected privilege escalation to the Domain Admins group',
    source: 'Audit',
    status: 'open',
  },
  {
    id: 'evt-010',
    timestamp: '2026-06-13T12:30:00Z',
    severity: 'critical',
    description: 'Active exploitation attempt against CVE-2026-1337',
    source: 'WAF',
    status: 'open',
    assignedTo: 'm.okafor',
  },
  {
    id: 'evt-011',
    timestamp: '2026-06-09T09:00:00Z',
    severity: 'medium',
    description: 'Outdated antivirus definitions on 12 hosts',
    source: 'Endpoint',
    status: 'resolved',
  },
  {
    id: 'evt-012',
    timestamp: '2026-06-12T19:25:00Z',
    severity: 'low',
    description: 'Concurrent VPN sessions from the same account',
    source: 'VPN',
    status: 'investigating',
  },
  {
    id: 'evt-013',
    timestamp: '2026-06-13T07:48:00Z',
    severity: 'high',
    description: 'Phishing campaign targeting the finance department',
    source: 'Email Gateway',
    status: 'open',
    assignedTo: 'j.silva',
  },
  {
    id: 'evt-014',
    timestamp: '2026-06-11T13:15:00Z',
    severity: 'medium',
    description: 'Cloud IAM access key unused for 90 days still active',
    source: 'Cloud IAM',
    status: 'open',
  },
]
